# --- Camera 1: 3DO Nozzle Cam ---
ENABLED_nozzle=1
DEVICE_nozzle=/dev/v4l/by-id/video2
PORT_nozzle=8081
RES_nozzle=2560x1440
FPS_nozzle=30
EXPO_AUTO_nozzle=1  # Auto exposure <-- 1 forces Manual Mode (0=Auto, 3=Aperture Priority)
EXPO_ABS_nozzle=700 # < Exposure absolute, only works in manual mode (3 min, 2047 max)